<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-FS7JD1M" name="LoginTS.LoginTC" tests="2" failures="1" timestamp="22 Feb 2020 12:11:18 GMT" time="32.403" errors="0">
  <testcase name="loginSuccessfully" time="11.316" classname="LoginTS.LoginTC"/>
  <testcase name="verifyLoginSuccessfullyMsg" time="21.087" classname="LoginTS.LoginTC">
    <failure type="java.lang.AssertionError" message="Unable to display successfully Msg expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: Unable to display successfully Msg expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertFalse(Assert.java:65)
at LoginTS.LoginTC.verifyLoginSuccessfullyMsg(LoginTC.java:81)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- verifyLoginSuccessfullyMsg -->
</testsuite> <!-- LoginTS.LoginTC -->
